//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingCompanyDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoddsInStock
    {
        public int GoodsInStockID { get; set; }
        public int GoodsID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Goods Goods { get; set; }
    }
}
